=== rafael123rr/CodeU-Summer-2018/kefir-bb-0.6/kefir-bb-0.5.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
            targetNamespace="http://kefir-bb.sourceforge.net/schemas"
            xmlns="http://kefir-bb.sourceforge.net/schemas"
            elementFormDefault="qualified"
            attributeFormDefault="unqualified">
    <!-- Template type description -->
    <xsd:complexType name="templateType" mixed="true">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="var">
                <xsd:complexType>
                    <xsd:attribute name="name" type="xsd:string" default="variable"/>
                </xsd:complexType>
            </xsd:element>
        </xsd:choice>
    </xsd:complexType>

    <!-- Code tag description -->
    <xsd:complexType name="codeType">
        <xsd:sequence>
            <xsd:element name="pattern">
                <xsd:complexType mixed="true">
                    <xsd:choice minOccurs="0" maxOccurs="unbounded">
                        <xsd:element name="var">
                            <xsd:complexType>
                                <xsd:attribute name="name" type="xsd:string" default="variable"/>
                                <xsd:attribute name="parse" type="xsd:boolean" default="true"/>
                                <xsd:attribute name="regex" type="xsd:string" default=".*"/>
                                <xsd:attribute name="scope" type="xsd:IDREF" default="ROOT"/>
                                <xsd:attribute name="inherit" type="xsd:boolean" default="false"/>
                                <xsd:attribute name="transparent" type="xsd:boolean" default="false"/>
                            </xsd:complexType>
                        </xsd:element>
                    </xsd:choice>
                </xsd:complexType>
            </xsd:element>
            <xsd:element name="template" type="templateType"/>
        </xsd:sequence>
        <xsd:attribute name="name" type="xsd:ID"/>
        <xsd:attribute name="priority" type="xsd:integer" default="0"/>
    </xsd:complexType>

    <xsd:element name="configuration">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element name="params" minOccurs="0" maxOccurs="1">
                    <xsd:complexType>
                        <xsd:choice minOccurs="0" maxOccurs="unbounded">
                            <xsd:element name="param">
                                <xsd:complexType>
                                    <xsd:attribute name="name" type="xsd:string" use="required"/>
                                    <xsd:attribute name="value" type="xsd:string" use="required"/>
                                </xsd:complexType>
                            </xsd:element>
                        </xsd:choice>
                    </xsd:complexType>
                </xsd:element>
                <xsd:element name="prefix" type="templateType" minOccurs="0" maxOccurs="1"/>
                <xsd:element name="suffix" type="templateType" minOccurs="0" maxOccurs="1"/>
                <xsd:choice minOccurs="0" maxOccurs="unbounded">
                    <xsd:element name="code" type="codeType"/>
                    <xsd:element name="scope">
                        <xsd:complexType>
                            <xsd:choice minOccurs="0" maxOccurs="unbounded">
                                <xsd:element name="coderef">
                                    <xsd:complexType>
                                        <xsd:attribute name="name" type="xsd:IDREF" use="required"/>
                                    </xsd:complexType>
                                </xsd:element>
                                <xsd:element name="code" type="codeType"/>
                            </xsd:choice>
                            <xsd:attribute name="name" type="xsd:ID" use="required"/>
                            <xsd:attribute name="parent" type="xsd:IDREF" use="optional"/>
                            <xsd:attribute name="ignoreText" type="xsd:boolean" use="optional" default="false"/>
                        </xsd:complexType>
                    </xsd:element>
                </xsd:choice>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>
</xsd:schema>

=== rafael123rr/CodeU-Summer-2018/kefir-bb-0.6/test/ru/perm/kefir/bbcode/blackbox/config-open.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://kefir-bb.sourceforge.net/schemas"
               xsi:schemaLocation="http://kefir-bb.sourceforge.net/schemas http://kefir-bb.sourceforge.net/schemas/kefir-bb-0.5.xsd">
    <code>
        <pattern><var name="name" regex="\w+"/>=<var name="value"/></pattern>
        <template>Set <var name="value"/> to <var name="name"/>.</template>
    </code>
</configuration>

=== rafael123rr/CodeU-Summer-2018/kefir-bb-0.6/test/ru/perm/kefir/bbcode/blackbox/config-transparent.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://kefir-bb.sourceforge.net/schemas"
               xsi:schemaLocation="http://kefir-bb.sourceforge.net/schemas
               http://kefir-bb.sourceforge.net/schemas/kefir-bb-0.5.xsd">
    <code>
        <pattern>&lt;<var name="name" regex="\w*"/> <var name="attrs" transparent="true"/>/&gt;</pattern>
        <template>tag=<var name="name"/>,a=<var name="a"/>,b=<var name="b"/>,c=<var name="c"/></template>
    </code>
    <code>
        <pattern>a=&quot;<var name="a"/>&quot;</pattern>
        <template/>
    </code>
    <code>
        <pattern>b=&quot;<var name="b"/>&quot;</pattern>
        <template/>
    </code>
    <code>
        <pattern>c=&quot;<var name="c"/>&quot;</pattern>
        <template/>
    </code>
</configuration>

=== rafael123rr/CodeU-Summer-2018/kefir-bb-0.6/test/ru/perm/kefir/bbcode/blackbox/config-scope-order.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://kefir-bb.sourceforge.net/schemas"
               xsi:schemaLocation="http://kefir-bb.sourceforge.net/schemas http://kefir-bb.sourceforge.net/schemas/kefir-bb-0.5.xsd">
    <scope name="ROOT" parent="sc">
        <code>
            <pattern>*<var/>*</pattern>
            <template>!<var/>!</template>
        </code>
    </scope>
    <scope name="sc">
        <code>
            <pattern>@<var/>@</pattern>
            <template>#<var/>#</template>
        </code>
    </scope>
</configuration>

=== rafael123rr/CodeU-Summer-2018/kefir-bb-0.6/test/ru/perm/kefir/bbcode/blackbox/config-scope.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://kefir-bb.sourceforge.net/schemas"
               xsi:schemaLocation="http://kefir-bb.sourceforge.net/schemas http://kefir-bb.sourceforge.net/schemas/kefir-bb-0.5.xsd">
    <scope name="ROOT">
        <coderef name="b1"/>
        <coderef name="b3"/>
        <code name="b4">
            <pattern>er</pattern>
            <template>ga</template>
        </code>
    </scope>
    <scope name="sc">
        <coderef name="b2"/>
    </scope>
    <code name="b1">
        <pattern>[<var scope="sc"/>]</pattern>
        <template>*<var/>*</template>
    </code>
    <code name="b2">
        <pattern>(<var/>)</pattern>
        <template>^<var/>^</template>
    </code>
    <code name="b3">
        <pattern>(</pattern>
        <template>:(</template>
    </code>
</configuration>

=== rafael123rr/CodeU-Summer-2018/kefir-bb-0.6/test/ru/perm/kefir/bbcode/blackbox/config-regex.xml
<?xml version="1.0" encoding="utf-8"?>
<configuration xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xmlns="http://kefir-bb.sourceforge.net/schemas"
               xsi:schemaLocation="http://kefir-bb.sourceforge.net/schemas http://kefir-bb.sourceforge.net/schemas/kefir-bb-0.5.xsd">
    <code>
        <pattern>def <var name="id" regex="\w+"/>=<var name="value" regex="\d+"/>;</pattern>
        <template><var name="id"/>:<var name="value"/></template>
    </code>
</configuration>
